export const CARD_DEFAULTS = [
  {
    imgSrc: "/images/png/clock.png",
        imgHover:"/images/png/product-1.png",
    title: "Newgate Wideboy Alarm Clock",
    discount: "Guadagna € 8,00",
    price: "€ 56,95",
    description: "description",
  },
  {
    imgSrc: "/images/png/made-crate-mini.png",
        imgHover:"/images/png/product-2.png",
    title: "Made Crate Mini",
    discount: "Guadagna € 12,00",
    price: "€ 8,95",
    description: "description",
  },
  {
    imgSrc: "/images/png/cusion-cover.png",
        imgHover:"/images/png/product-5.png",
    title: "NouNou Jae Cusion Cover",
    discount: "Guadagna € 8,00",
    price: "€ 40,95",
    description: "description",
  },
  {
    imgSrc: "/images/png/doiy-bobby-vase.png",
        imgHover:"/images/png/product-6.png",
    title: "DOIY Bobby Vase",
    discount: "Guadagna € 8,00",
    price: "€ 47,95",
    description: "description",
  },
  {
    imgSrc: "/images/png/curvies-socks.png",
        imgHover:"/images/png/product-7.png",
    title: "Eat My Socks Curvies Socks",
    discount: "Guadagna € 10,00",
    price: "€ 15,95",
    description: "description",
  },
  {
    imgSrc: "/images/png/habichl-burger.png",
        imgHover:"/images/png/product-8.png",
    title: "Habichl Burger Coasters Set",
    discount: "Guadagna € 22,00",
    price: "€ 95,95",
    description: "description",
  },
  {
    imgSrc: "/images/png/bottle.png",
        imgHover:"/images/png/product-9.png",
    title: "FRAMA Hand Wash, 375ml",
    discount: "Guadagna € 8,00",
    price: "€ 47,95",
    description: "description",
  },
  {
    imgSrc: "/images/png/cup.png",
        imgHover:"/images/png/product-10.png",
    title: "NouNou Friends Mug",
    discount: "Guadagna € 12,00",
    price: "€ 33,95",
    description: "description",
  },
  {
    imgSrc: "/images/png/both.png",
        imgHover:"/images/png/product-11.png",
    title: "DETAIL Feline 5 Nesting Dolls",
    discount: "Guadagna € 8,00",
    price: "€ 37,95",
    description: "description",
  },

];